
= Capítulo 7. Conclusiones y Trabajos Futuros

== Conclusiones

El presente trabajo de tesis ha demostrado la viabilidad técnica de integrar el paradigma de paralelismo basado en directivas en el ecosistema del lenguaje Go mediante el diseño, la implementación y la evaluación de la herramienta GompherMP: un compilador _source-to-source_ y una librería de runtime que transforma automáticamente anotaciones de alto nivel en código concurrente nativo de Go. Los resultados obtenidos constituyen evidencia empírica sobre las condiciones bajo las cuales este paradigma es efectivo en un lenguaje de propósito general moderno, así como sobre las limitaciones que aún persisten en la implementación actual. En conjunto, estos hallazgos responden de manera parcial al problema central identificado en esta investigación.

En el Capítulo 4, se cumplió con el primer objetivo específico (OE1) mediante la elaboración de la especificación completa de GompherMP. Se definió la sintaxis y semántica de un subconjunto de directivas inspirado en OpenMP, incluyendo `parallel for`, `reduction`, `schedule`, `task`, `taskloop`, `taskgroup`, `taskwait`, `depend`, `single`, `barrier` y `parallel sections`, junto con las transformaciones de código asociadas a cada una de ellas y la especificación funcional de la interfaz de línea de comandos (CLI). Este diseño abordó directamente el primero de los problemas causa identificados en el árbol de problemas: la divergencia semántica entre el modelo de directivas y las abstracciones de concurrencia nativas de Go. La resolución de esta divergencia requirió tomar decisiones de diseño no triviales: la elección de comentarios `//gompher` como mecanismo de anotación, la correspondencia entre regiones paralelas y _pools_ de goroutines persistentes, y el modelo de dependencias explícitas para el paralelismo de tareas, todas documentadas en los resultados R1, R2 y R3.

En el Capítulo 5, se cumplió con el segundo objetivo específico (OE2) a través de la implementación de la infraestructura central de GompherMP, organizada en tres módulos del runtime, a saber, gestión de goroutines y reparto de trabajo (R4), mecanismos de sincronización (R5) y paralelismo de tareas con dependencias (R6), y tres componentes del compilador: el analizador sintáctico de directivas (R7), el motor de transformación del AST (R8) y la herramienta CLI funcional (R9). Este objetivo atendió el segundo problema causa: la alta complejidad inherente en la transformación de código para mapear directivas hacia las primitivas de concurrencia de Go. La solución adoptó una arquitectura de compilación _source-to-source_ sobre el AST nativo de Go, lo que permitió generar código concurrente portable y compilable con el _toolchain_ estándar sin modificaciones al propio compilador del lenguaje.

En el Capítulo 6, se cumplió con el tercer objetivo específico (OE3) a través de una evaluación cuantitativa y cualitativa que abarcó tres resultados esperados. R10 se materializó en una suite de diez _benchmarks_ de cómputo intensivo implementados en tres variantes (secuencial, paralela manual y paralela con GompherMP), cubriendo los principales patrones de paralelismo que un desarrollador Go puede encontrar en aplicaciones de propósito general. R11 consolidó el análisis de rendimiento y escalabilidad: GompherMP superó al código manual idiomático en _Reduce_ ($13.35 times$ vs. $7.66 times$), igualó a _N-Queens_ ($9.44 times$ vs. $9.39 times$) y _Pipeline_ ($2.64 times$ vs. $2.37 times$), y mostró rendimiento inferior en los _benchmarks_ con grano de tarea muy fino o con recursión paralela de profundidad variable, con causas implementativas identificadas y diferenciadas de las del modelo. R12 completó el análisis con el reporte de expresividad y productividad: para los patrones _data-parallel_ con reducción, GompherMP reduce el LoC entre un 50% y un 71%, mientras que para los grafos de dependencias de tareas el LoC aumenta hasta un 144%, aunque con ganancia en legibilidad declarativa del flujo de datos. Este tercer objetivo atendió el tercer problema causa: la insuficiencia de implementaciones de referencia y de evidencia empírica que validen la viabilidad del paradigma fuera del ecosistema tradicional de C, C++ y Fortran.

Los tres objetivos específicos se cumplieron satisfactoriamente dentro del alcance definido. El objetivo general, que consiste en diseñar, desarrollar y evaluar GompherMP a fin de cerrar la brecha semántica y de abstracción entre el paradigma de directivas y los ecosistemas de lenguajes de propósito general modernos, también se cumplió: la herramienta existe, es funcional, transpila correctamente los diez _benchmarks_ de la suite y los resultados de la evaluación caracterizan con precisión sus fortalezas y sus limitaciones.

Sin embargo, la resolución del problema central es *parcial*. El problema formulado en esta investigación es de alcance general, pues abarca la brecha semántica en los ecosistemas de lenguajes modernos en plural, pero la solución desarrollada circunscribe la implementación a Go como lenguaje objetivo. Adicionalmente, la implementación actual de GompherMP presenta cuatro limitaciones técnicas identificadas: la resolución de la identidad de goroutine mediante introspección del _stack trace_, la ausencia de un equivalente a `omp_get_thread_num()`, la incapacidad de `taskloop` para expresar recursión paralela de profundidad variable y el _overhead_ por tarea en `TaskWithDepend` para grano muy fino, limitaciones que impiden que la herramienta alcance el rendimiento del código manual en todos los patrones evaluados. La evidencia empírica demuestra que el paradigma _es viable_ para Go y que supera al enfoque manual en los patrones de paralelismo más habituales, pero la generalización del resultado a otros lenguajes y la corrección de las limitaciones de rendimiento identificadas quedan fuera del alcance de este trabajo y configuran la agenda de investigación futura.

Las implicaciones de estos resultados son relevantes para la comunidad de desarrolladores Go y para la investigación en compiladores de paralelismo. En primer lugar, GompherMP confirma que el modelo de directivas no está intrínsecamente acoplado a los lenguajes de sistemas: es posible implementarlo sobre las primitivas de concurrencia de un lenguaje con planificador de goroutines y recolector de basura, obteniendo rendimiento competitivo para los patrones de mayor frecuencia. En segundo lugar, el análisis de expresividad provee evidencia cuantitativa y cualitativa de que el paradigma reduce la carga cognitiva del programador al eliminar el _boilerplate_ de concurrencia, compuesto por goroutines explícitas, canales, `sync.WaitGroup` y `sync.Mutex`, que es también la fuente más frecuente de errores documentada en el ecosistema de Go (Tu et al., 2019). En tercer lugar, la caracterización precisa de los cuatro casos donde GompherMP pierde rendimiento frente al manual constituye, por sí misma, una contribución: delimita el subespacio del problema donde el paradigma requiere extensiones de modelo o mejoras de implementación, información que no existía previamente para Go.


== Trabajos Futuros

Como primera línea de trabajo futuro, se propone resolver las cuatro limitaciones de implementación identificadas en la evaluación. La sustitución de `getGoroutineID()` por un identificador de contexto pasado explícitamente al _pool_ eliminaría la latencia de introspección del _stack trace_ que penaliza a _PrefixSum_ en presencia de `barrier` y `single` frecuentes. La incorporación de un mecanismo análogo a `omp_get_thread_num()`, concretamente un entero de ranura de goroutine accesible desde el cuerpo de la directiva, permitiría que `parallel for` inicialice estado local por goroutine, resolviendo la limitación de _MonteCarlo_ y habilitando un conjunto más amplio de algoritmos estocásticos. La extensión del planificador de `taskloop` con particionado adaptativo basado en _work-stealing_ superaría la restricción de grano fijo que impide modelar la recursión paralela de _QuickSort_. Finalmente, la optimización del camino crítico de `TaskWithDepend` mediante una estructura de dependencias sin _lock_ global y asignación de tareas en un _pool_ preasignado reduciría el _overhead_ por tarea que penaliza a _Fibonacci (depend)_ para grano submilisegundo. Estas mejoras, individualmente verificables con la suite de _benchmarks_ existente, constituyen la agenda de ingeniería más directamente motivada por los resultados de esta tesis.

Como segunda línea, se propone ampliar la cobertura de la especificación de directivas de GompherMP hacia un subconjunto más completo del estándar OpenMP. El trabajo actual cubre los constructos de nivel de tarea y de bucle; quedan fuera `simd` (vectorización explícita), las cláusulas `reduction` sobre `taskloop` (actualmente el programador debe gestionar manualmente la acumulación de resultados parciales, como ilustra el caso _Fibonacci taskloop_), las directivas `atomic` con semántica completa de lectura-modificación-escritura y el constructo `target` para _offloading_ a dispositivos heterogéneos. La incorporación de `reduction` en `taskloop` es especialmente relevante dado el análisis de expresividad: eliminaría el único caso donde `taskloop` requiere más LoC que el manual sin aporte de legibilidad declarativa. Extender la especificación en esta dirección, acompañada de la correspondiente expansión de la suite de _benchmarks_, fortalecería tanto la comparabilidad con OpenMP como la utilidad práctica de la herramienta.

Como tercera línea, se propone trasladar el paradigma implementado a otros lenguajes de propósito general modernos con modelos de concurrencia distintos al de Go: Rust (con su sistema de tipos de propiedad y sin recolector de basura), Python (en su implementación CPython con GIL o en PyPy con STM) y Kotlin sobre la JVM (con corrutinas estructuradas). Esta extensión respondería al componente del problema central que el presente trabajo abordó solo parcialmente: la viabilidad del paradigma en los _ecosistemas_ modernos en sentido amplio. Para cada lenguaje, los desafíos de mapeo serán cualitativamente distintos; en Rust, por ejemplo, la seguridad de memoria en tiempo de compilación impone restricciones sobre el modelo de regiones paralelas con datos compartidos que requerirán adaptaciones no triviales de la especificación, y los resultados de la evaluación cruzada permitirán identificar qué características del modelo son transferibles y cuáles son específicas del modelo de concurrencia de Go.

Como cuarta línea, de naturaleza más exploratoria, se propone integrar análisis estático de condiciones de carrera en el propio compilador de GompherMP. El transpilador ya dispone de una representación completa del flujo de datos entre directivas a través del grafo de dependencias construido para `task depend`; extender este análisis hacia las directivas de bucle y de sincronización permitiría detectar en tiempo de compilación accesos concurrentes no protegidos a variables compartidas, emitiendo advertencias antes de generar el código de salida. Esta integración convertiría a GompherMP en una herramienta que no solo reduce la carga cognitiva de paralelizar código, sino que también refuerza activamente la corrección de la paralelización, abordando así el tercer efecto adverso identificado en el árbol de problemas: el aumento del riesgo de errores de concurrencia al paralelizar manualmente en lenguajes modernos.
