package printer

import (
	"go/parser"
	"go/token"
	"os"
	"strings"
	"testing"

	gparser "github.com/gomphermp/gomphermp/internal/parser"
	"github.com/gomphermp/gomphermp/internal/transformer"
)

// TestPrint_RoundTrip verifies that printing a parsed file produces valid Go
// source that contains the same top-level identifiers as the original.
func TestPrint_RoundTrip(t *testing.T) {
	src := `package main

import "fmt"

func main() {
	fmt.Println("hello")
}
`
	parsed, err := gparser.Parse(src)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	f, err := os.CreateTemp("", "gompher_test_*.go")
	if err != nil {
		t.Fatalf("create temp: %v", err)
	}
	path := f.Name()
	f.Close()
	defer os.Remove(path)

	if err := Print(parsed, path); err != nil {
		t.Fatalf("Print: %v", err)
	}

	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}

	got := string(out)

	// Output must be parseable Go
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "", got, 0); err != nil {
		t.Errorf("output is not valid Go: %v\ngot:\n%s", err, got)
	}

	for _, want := range []string{"package main", `"fmt"`, "fmt.Println"} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q in output, got:\n%s", want, got)
		}
	}
}

// TestPrint_TransformedOutput verifies that after parsing and transforming a
// file with a //gompher task directive, Print emits the runtime.Task call and
// the runtime import.
func TestPrint_TransformedOutput(t *testing.T) {
	src := `package main

func main() {
	//gompher task
	{
		work()
	}
}

func work() {}
`
	parsed, err := gparser.Parse(src)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	transformed, err := transformer.Transform(parsed)
	if err != nil {
		t.Fatalf("transform: %v", err)
	}

	f, err := os.CreateTemp("", "gompher_test_*.go")
	if err != nil {
		t.Fatalf("create temp: %v", err)
	}
	path := f.Name()
	f.Close()
	defer os.Remove(path)

	if err := Print(transformed, path); err != nil {
		t.Fatalf("Print: %v", err)
	}

	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}

	got := string(out)

	for _, want := range []string{
		`"github.com/gomphermp/gomphermp/pkg/runtime"`,
		"runtime.Task(func() {",
		"work()",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q in output, got:\n%s", want, got)
		}
	}

	// Directive comment must be gone
	if strings.Contains(got, "//gompher") {
		t.Errorf("expected directive comment removed, got:\n%s", got)
	}
}

// TestPrint_AddsGeneratedHeader verifies that the output begins with the
// standard machine-generated header, on its own line before the package
// clause, so editors and tooling recognize the file as non-canonical source.
func TestPrint_AddsGeneratedHeader(t *testing.T) {
	got := printSource(t, `package main

func main() {}
`)

	if !strings.HasPrefix(got, "// Code generated by GompherMP. DO NOT EDIT.\n") {
		t.Errorf("expected generated header at the top, got:\n%s", got)
	}
	// The header must match Go's recognized convention.
	if !strings.Contains(got, "// Code generated ") || !strings.Contains(got, "DO NOT EDIT.") {
		t.Errorf("header does not match the Go generated-code convention, got:\n%s", got)
	}
}

// TestPrint_StripsComments verifies that the printer drops all comments. This
// is the workaround for the go/ast free-floating-comment defect (issue 20744):
// once the transformer moves nodes, surviving comments would be misplaced, so
// the printer emits none. The output must still be valid, comment-free Go.
func TestPrint_StripsComments(t *testing.T) {
	got := printSource(t, `// package doc comment
package main

import "fmt"

func main() {
	// inner comment
	fmt.Println("x") // trailing comment
}
`)

	// The generated header is the only // line; no source comment survives.
	for _, gone := range []string{"package doc comment", "inner comment", "trailing comment"} {
		if strings.Contains(got, gone) {
			t.Errorf("expected source comment %q to be stripped, got:\n%s", gone, got)
		}
	}
	// And the code itself is preserved.
	if !strings.Contains(got, `fmt.Println("x")`) {
		t.Errorf("expected code preserved, got:\n%s", got)
	}
}

// printSource is a helper that parses src, prints it to a temp file, and
// returns the resulting output text.
func printSource(t *testing.T, src string) string {
	t.Helper()
	parsed, err := gparser.Parse(src)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	f, err := os.CreateTemp("", "gompher_test_*.go")
	if err != nil {
		t.Fatalf("create temp: %v", err)
	}
	path := f.Name()
	f.Close()
	defer os.Remove(path)

	if err := Print(parsed, path); err != nil {
		t.Fatalf("Print: %v", err)
	}
	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	return string(out)
}

// TestPrint_BadPath verifies that Print returns a non-nil error when the
// destination path is not writable (e.g. directory does not exist).
func TestPrint_BadPath(t *testing.T) {
	src := `package main

func main() {}
`
	parsed, err := gparser.Parse(src)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	err = Print(parsed, "/nonexistent_dir_gompher/output.go")
	if err == nil {
		t.Fatal("expected error for non-writable path, got nil")
	}
}
