// Package printer converts a parsed (and optionally transformed) Go AST back
// into gofmt-canonical Go source and writes it to a file on disk.
package printer

import (
	"bytes"
	"go/format"
	"os"

	"github.com/gomphermp/gomphermp/internal/parser"
)

// generatedHeader marks the output as machine-generated so editors
// and tooling recognize the file as non-canonical source.
const generatedHeader = "// Code generated by GompherMP. DO NOT EDIT.\n\n"

// Print formats result's AST using gofmt rules and writes the output to the
// file at path, creating or truncating it as needed.
//
// Comments are dropped before printing. This sidesteps the long-standing
// go/ast free-floating-comment defect (golang.org/issue/20744): comments are
// positioned by source offset rather than attached to nodes, so once the
// transformer moves nodes around, go/printer places the original comments at
// now-incorrect spots. With no comments to reposition the defect cannot
// trigger. The generated file is a build artifact, so the user's
// source keeps its comments.
func Print(result *parser.ParseResult, path string) error {
	result.File.Comments = nil
	result.File.Doc = nil

	var buf bytes.Buffer
	// Defensive: format.Node only errors on a malformed AST, which Transform
	// never produces - a valid AST formats cleanly, a broken one makes go/format
	// panic rather than return an error - so this branch is unreachable in normal
	// operation and cannot be exercised from a test.
	if err := format.Node(&buf, result.FileSet, result.File); err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	// Defensive: a write that fails after Create succeeded requires an exotic
	// descriptor (a full disk, /dev/full, a closed pipe); not reproducible in a
	// portable test.
	if _, err := f.WriteString(generatedHeader); err != nil {
		return err
	}
	_, err = buf.WriteTo(f)
	return err
}
